
--THUC HANH 3--
--CÂU 1--
CREATE FUNCTION TONGSL_BAN(@MA_NV INT)
RETURNS TABLE
AS
RETURN
	SELECT SUM(SoLuong) AS TONG
	FROM CTHOADON, HOADON, NHANVIEN
	WHERE CTHOADON.MaHD=HOADON.MaHD
		AND HOADON.MaNV=NHANVIEN.MaNV
		AND NHANVIEN.MaNV=@MA_NV
		--drop function TONGSL_BAN--
SELECT * FROM TONGSL_BAN(1)

--CÂU 2--
CREATE FUNCTION TONGSL_MUA (@MA_KH NVARCHAR(10))
RETURNS TABLE
AS
RETURN
	SELECT SUM(SoLuong) AS TONG
	FROM CTHOADON, HOADON, KHACHHANG
	WHERE CTHOADON.MaHD=HOADON.MaHD
		AND HOADON.MaHD=CTHOADON.MaHD
		AND HOADON.MaKH=KHACHHANG.MaKH
		AND KHACHHANG.MaKH=@MA_KH
		drop function TONGSL_MUA
	SELECT * FROM TONGSL_MUA('lixco')

--Câu 3--
CREATE FUNCTION ThongTin_KH_MuaNh ()
RETURNS TABLE
AS
RETURN 
	(SELECT	TOP(1) A.MaKH, TenKH, DiaChi, ThanhPho, DienThoai
	FROM KHACHHANG A, 
	(SELECT B.MaKH AS MAKH, SUM(A.SoLuong) as TONGSL
	FROM CTHOADON A, HOADON B, KHACHHANG C
	WHERE C.MaKH=B.MaKH
		GROUP BY  B.MaKH) D
	WHERE A.MaKH=D.MAKH
		ORDER BY D.TONGSL DESC)
		
	SELECT * FROM ThongTin_KH_MuaNh ()
	
--Câu 4--
CREATE FUNCTION ThongTin_NV_BanNh()
RETURNS TABLE
AS
RETURN 
	(SELECT TOP(1) A.MaNV,HoNV,TenNV,Phai,DienThoai
	FROM NHANVIEN A,
	(SELECT B.MaNV AS MNV , SUM(A.SoLuong) as TONGSL
	FROM CTHOADON A,HOADON B, NHANVIEN C
	WHERE C.MaNV=B.MaNV
		GROUP BY B.MaNV) D
	WHERE A.MaNV=D.MNV
		ORDER BY D.TONGSL DESC)

	SELECT * FROM ThongTin_NV_BanNh()

--CÂU 5--
CREATE FUNCTION ThongTin_SP_BanNh()
RETURNS TABLE
AS
RETURN
	SELECT MaSP,TenSP,DonGia FROM SANPHAM,
	(SELECT A.MaSP AS MSP, SUM(A.SoLuong) as TONG
	FROM CTHOADON A,HOADON B, SANPHAM C
	WHERE A.MaSP=C.MaSP AND A.MaHD = B.MaHD	GROUP BY A.MaSP) D
	WHERE SANPHAM.MaSP=D.MSP
	ORDER BY D.TONG DESC
	
	SELECT * FROM ThongTin_SP_BanNh()

--CÂU 6--
CREATE FUNCTION QUY()
RETURNS TABLE
AS
RETURN SELECT SUM(A.SoLuong) AS SLMOIQUY,C.QUY FROM CTHOADON A,
(SELECT B.MaHD AS MAHOADON, DATEPART(QUARTER,A.NgayLapHD)AS QUY
FROM HOADON A,CTHOADON B
WHERE A.MaHD=B.MaHD GROUP BY A.NgayLapHD,B.MaHD) C
WHERE C.MAHOADON=A.MaHD
GROUP BY C.QUY

SELECT * FROM QUY()

--CÂU 7--
CREATE FUNCTION TTHOADON (@SOHOADON NVARCHAR(5))
RETURNS TABLE 
AS
	RETURN (SELECT A.MAKH, A.TENKH,D.TenSP,A.DiaChi,A.DIENTHOAI, A.ThanhPho, C.SOLUONG,C.THANHTIEN FROM KHACHHANG A, HOADON B , CTHOADON C,SANPHAM D
	WHERE A.MaKH=B.MaKH AND B.MaHD=C.MaHD AND D.MaSP=C.MaSP AND B.MaHD=@SOHOADON)
	--GOI HAM
	SELECT * FROM TTHOADON ('10148')


	drop function TTHOADON


	----II. THU TUC----
	
	---- CAU 1----
	CREATE PROC THEMHANGHOA( @MASP SMALLINT, @TENSP NVARCHAR(40),
	@DONVITINH NVARCHAR(10), @DONGIA MONEY, @SL_TON INT )
	AS
	INSERT INTO SANPHAM VALUES (@MASP,@TENSP,@DONVITINH,@DONGIA,@SL_TON)

	EXEC  THEMHANGHOA '21','SATORI','CHAI', '6000',''
	GO
	----CAU 2----
	CREATE PROC TINHTONKHO @MASP SMALLINT
	AS
	SELECT SOLUONGTON FROM SANPHAM WHERE MASP=@MASP
	
	EXEC TINHTONKHO 2
	---- CAU 3----
	CREATE PROC XUATTT @MANV SMALLINT
	AS
	SELECT MaHD FROM NHANVIEN A, HOADON B
	WHERE A.MaNV=@MANV AND A.MANV=B.MaNV
	
	EXEC XUATTT 5
	----CAU 4----
	CREATE PROC TTHOADON_PROC @MAKH NVARCHAR(10)
	AS
	SELECT * FROM KHACHHANG A
	WHERE A.MaKH=@MAKH 
	
	EXEC TTHOADON_PROC 'BSCO'
	----CAU 5----
	CREATE PROC HOADONTHOIHAN @NGAYLAPHD DATE
	AS
	SELECT * FROM HOADON
	WHERE HOADON.NgayLapHD= @NGAYLAPHD

	 EXEC HOADONTHOIHAN '2009/01/12'

	 CREATE PROC TIMHOADON @SDT NVARCHAR(14),@DIACHI NVARCHAR(40), @tenkh nvarchar(25)
	 AS
	 SELECT tenkh, mahd FROM HOADON A, KHACHHANG B
	 WHERE A.MaKH=B.MaKH 
	 AND B.DienThoai= @SDT AND B.DiaChi=@DIACHI and b.TenKH= @tenkh	

	 EXEC TIMHOADON '8218509','12 Thuận Kiều Q5'

	 drop PROC TIMHOADON
