CREATE DATABASE QLDA
GO
USE QLDA
GO
CREATE TABLE PHONGBAN
( MAPHG INT PRIMARY KEY,
TENPHG CHAR(10),
TRPHG CHAR(3),
NG_NHANCHUC DATETIME)

CREATE TABLE NHANVIEN 
( MANV CHAR(3) PRIMARY KEY,
HONV CHAR(20),
TENLOT CHAR(20),
TENNV CHAR(20),
NGSINH DATETIME,
PHAI CHAR(3),
DCHI CHAR(100),
MA_NQL CHAR(3),
PHG INT,
LUONG FLOAT 
)
CREATE TABLE DEAN 
( MADA INT PRIMARY KEY,
TENDA CHAR(30),
DDIEM_DA CHAR(100),
PHONG INT
)
CREATE TABLE PHANCONG
(MA_NVIEN CHAR(3),
SODA INT,
THOIGIAN FLOAT)

CREATE TABLE DIADIEM_PHG
(MAPHG INT PRIMARY KEY,
DIADIEM CHAR(30))

CREATE TABLE THANNHAN
(MA_NVIEN CHAR(3) PRIMARY KEY,
TENTV CHAR(50),
PHAI VARCHAR(5) not null,
NGSINH DATETIME,
QUANHE CHAR(30)
)


INSERT INTO PHONGBAN (MAPHG,TENPHG,TRPHG,NG_NHANCHUC)
VALUES ('1','QUAN LY','888','06/19/1971')
INSERT INTO PHONGBAN (MAPHG,TENPHG,TRPHG,NG_NHANCHUC)
VALUES ('4','DIEUHANH','777','01/01/1985')
INSERT INTO PHONGBAN (MAPHG,TENPHG,TRPHG,NG_NHANCHUC)
VALUES ('5','NGHIENCUU','333','05/22/1978')

INSERT INTO NHANVIEN (HONV,TENLOT,TENNV,MANV,NGSINH,PHAI, DCHI,MA_NQL,PHG,LUONG)
VALUES ('DINH','BA','TIEN','123','01/09/1955','NAM',' 731 Tran Hung Dao Q1','333','5',30000)
INSERT INTO NHANVIEN (HONV,TENLOT,TENNV,MANV,NGSINH,PHAI, DCHI,MA_NQL,PHG,LUONG)
VALUES ('NGUYEN','THANH','TUNG','333','08/12/1945','NAM',' 638 Nguyen Van Cu Q5','888','5',40000)
INSERT INTO NHANVIEN (HONV,TENLOT,TENNV,MANV,NGSINH,PHAI, DCHI,MA_NQL,PHG,LUONG)
VALUES ('TRAN','THANH','TAM','453','31/07/1962','NAM',' 543 MAI THI Luu Ba Dinh Ha','333','5',25000)
INSERT INTO NHANVIEN (HONV,TENLOT,TENNV,MANV,NGSINH,PHAI, DCHI,MA_NQL,PHG,LUONG)
VALUES ('NGUYEN','MANH','HUNG','666','09/15/1952','NAM',' 975 Le Lai P3 Vung Tau','333','5',38000)

INSERT INTO NHANVIEN (HONV,TENLOT,TENNV,MANV,NGSINH,PHAI, DCHI,MA_NQL,PHG,LUONG)
VALUES ('VUONG','NGOC','QUYEN','888','10/10/1927','NU',' 450 Trung Vuong My Tho TG','','1',55000)
INSERT INTO NHANVIEN (HONV,TENLOT,TENNV,MANV,NGSINH,phAI, DCHI,MA_NQL,PHG,LUONG)
VALUES ('LE','THI','NHAN','987','06/20/1931','NU','  291 Ho Van Hue Q.PN','888','4',43000)

INSERT INTO NHANVIEN (HONV,TENLOT,TENNV,MANV,NGSINH,PHAI, DCHI,MA_NQL,PHG,LUONG)
VALUES ('TRAN','HONG','QUANG','777','03/29/1959','NAM',' 980 Le Hong Phong Vung Tau ','987','4',25000)
INSERT INTO NHANVIEN (HONV,TENLOT,TENNV,MANV,NGSINH,PHAI, DCHI,MA_NQL,PHG,LUONG)
VALUES ('BUI','THUY','VU','999','07/19/1958','NAM',' 332 Nguyen Thai Hoc Quy','987','4',25000)


INSERT INTO DEAN(MADA,TENDA,DDIEM_DA,PHONG)
VALUES('1', 'SAN PHAM X','VUNG TAU','5')
INSERT INTO DEAN(MADA,TENDA,DDIEM_DA,PHONG)
VALUES('2', 'SAN PHAM Y','NHA TRANG','5')
INSERT INTO DEAN(MADA,TENDA,DDIEM_DA,PHONG)
VALUES('3', 'SAN PHAM Z','TP HCM','5')
INSERT INTO DEAN(MADA,TENDA,DDIEM_DA,PHONG)
VALUES('10', 'TIN HOC HOA','HA NOI','4')
INSERT INTO DEAN(MADA,TENDA,DDIEM_DA,PHONG)
VALUES('20', 'CAP QUANG','TP HCM','1')
INSERT INTO DEAN(MADA,TENDA,DDIEM_DA,PHONG)
VALUES('30', 'DAO TAO','HA NOI','4')

INSERT INTO DIADIEM_PHG(MAPHG,DIADIEM)
VALUES('1','TP HCM')
INSERT INTO DIADIEM_PHG(MAPHG,DIADIEM)
VALUES('4','HA NOI')
INSERT INTO DIADIEM_PHG(MAPHG,DIADIEM)
VALUES('5','NHA TRANG')
INSERT INTO DIADIEM_PHG(MAPHG,DIADIEM)
VALUES('5','TP HCM')
INSERT INTO DIADIEM_PHG(MAPHG,DIADIEM)
VALUES('5','VUNG TAU')

INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('123','1','22.5')
INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('123','2','7.5')
INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('123','3','10')

INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('333','10','10')
INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('333','20','10')
INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('453','1','20')
INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('453','2','20')
INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('666','3','40')
INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('888','20','0')
INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('987','20','15')
INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('987','30','20')
INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('777','10','35')
INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('777','30','5')
INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('999','10','10')
INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
VALUES('999','30','30')

INSERT INTO THANNHAN(MA_NVIEN,TENTV,PHAI,NGSINH,QUANHE)
VALUES('123','CHAU','NU','12/31/1978','CONGAI')
INSERT INTO THANNHAN(MA_NVIEN,TENTV,PHAI,NGSINH,QUANHE)
VALUES('123','DUY','NAM','01/01/1978','CONTRAI')
INSERT INTO THANNHAN(MA_NVIEN,TENTV,PHAI,NGSINH,QUANHE)
VALUES('123','PHUONG','NU','05/05/1957','Vo chong')
INSERT INTO THANNHAN(MA_NVIEN,TENTV,PHAI,NGSINH,QUANHE)
VALUES('333','Duong ','NU','05/03/1948','Vo chong')
INSERT INTO THANNHAN(MA_NVIEN,TENTV,PHAI,NGSINH,QUANHE)
VALUES('333','Tung','NAM','10/25/1973','CONTRAI')
INSERT INTO THANNHAN(MA_NVIEN,TENTV,PHAI,NGSINH,QUANHE)
VALUES('333','QUANG','NU','04/05/1976','CONGAI')
INSERT INTO THANNHAN(MA_NVIEN,TENTV,PHAI,NGSINH,QUANHE)
VALUES(' 987','Dang ','NAM','02/29/1932','Vo chong')
1
select HONV, TENLOT,TENNV
from nhanvien	
where phg=4
2
SELECT HONV, TENLOT,TENNV, LUONG
FROM NHANVIEN
WHERE LUONG>30000
3
select HONV, TENLOT,TENNV
from nhanvien	
where phg=4 and luong>25000 or luong>30000 and phg=5
4
select HONV, TENLOT,TENNV
from nhanvien	
where dchi like '%Q%'
5
select HONV, TENLOT,TENNV
from nhanvien	
where honv like 'n%'
6
select ngsinh, DCHI
from nhanvien	
where manv =123
8
select HONV, TENLOT,TENNV ,year(ngsinh) as 'Năm sinh'
from nhanvien	
/*cau9*/
select HONV, TENLOT,TENNV, year(getdate())-year(ngsinh) as 'Tuổi'
from nhanvien	
10


select HONV, TENLOT,TENNV
from nhanvien	
where phg=4
SELECT soda
from nhanvien, phancong
where MA_NVIEN=MANV and HONV= 'NGUYEN'
UNION 
SELECT MADA
FROM DEAN, PHONGBAN, NHANVIEN
WHERE PHONG=MAPHG AND TRPHG=MANV AND HONV='NGUYEN'

SELECT MANV, TENNV 
FROM THANNHAN TN , NHANVIEN NV
WHERE MA_NVIEN=MANV
AND TENTV=TENNV


select PHG , PB.TENPHG, AVG(LUONG) AS 'LUONG TB NHANVIEN'
FROM NHANVIEN NV , PHONGBAN PB
WHERE NV.PHG=PB.MAPHG
GROUP BY PHG, PB.TENPHG
HAVING AVG(LUONG)>20000


-- Cau 1]
/*Tạo trigger khi thêm nhân viên mới thì lương phải từ 2000 trở lên. 
Nếu dữ liệu không hợp lệ thì không cho thêm vào và xuất hiện 
thông báo “Lương nhân viên phải lớn hơn 2000*/
 
  create trigger tg_Themnv1
  on NHANV
  FOR INSERT
  AS
  BEGIN
        IF (SELECT LUONG FROM inserted) >2000
 
		BEGIN
		PRINT 'THEM NHAN VIEN MOI'
	
		 
		END
		ELSE 
		 BEGIN
		 	PRINT 'NHAN VIEN PHAI LON HON 2000'
		 END

 END

     INSERT INTO NHANV(HONV,TENLOT,TENNV,MANV,NGSINH,PHAI, DCHI,MA_NQL,PHG,LUONG)
     VALUES ('NGUYEN','HONG','HA','867','02/27/1959','NAM',' 981 Le Hong Phong Vung Tau ','987','4',1900)
--CAU 1B
   create trigger tg_kiemtraTuoiNV on nhanvien for insert
   AS
   begin
              if exists (select * from inserted where phai = 'Nam' and (DATEDIFF(year,ngsinh,getdate()) not between
         18 and 60))
         begin
            print N'Nhân viên Nam phải có tuổi từ 18 tới 60'
         rollback transaction
         end
        if exists (select * from inserted where phai = 'Nu' and (DATEDIFF(year,ngsinh,getdate()) not between
18 and 55))
       begin
       print N'Nhân viên Nữ phải có tuổi từ 18 tới 55'
       rollback transaction
       end
end

--Tạo trigger cho hành động cập nhật lương nhân viên với điều kiện lương mới phải lớn hơn lương cũ

  CREATE TRIGGER TG_CAPNHATNV1
  ON NHANV
  FOR UPDATE 
  AS
  BEGIN
      IF (SELECT LUONG FROM  INSERTED  )>30000
	  BEGIN 
	   PRINT 'LUONG NHAN VIEN PHAI LON HON 2000'
	   rollback transaction
	  END
     
  END

  UPDATE NHANV
  SET  LUONG = 20000
  WHERE MANV='999'

  select *
  from NHANV where manv = '999'

  -- 2B .Hiển thị tổng số nhân viên nữ, tổng số nhân viên nam sau khi có hành động thêm mới nhân viên
  create trigger tg_Themnv1
  on NHANV
  FOR INSERT
  AS
  BEGIN
        IF (SELECT LUONG FROM inserted) >2000
 
		BEGIN
		PRINT 'THEM NHAN VIEN MOI'
	
		 
		END
		ELSE 
		 BEGIN
		 	PRINT 'NHAN VIEN PHAI LON HON 2000'
		 END

 END

      INSERT INTO NHANV(HONV,TENLOT,TENNV,MANV,NGSINH,PHAI, DCHI,MA_NQL,PHG,LUONG)
     VALUES ('NGUYEN','HONG','DANG','897','02/27/1959','NU',' 981 Le Hong Phong Vung Tau ','987','4',1900)
  
   SELECT COUNT(PHAI) AS' TONG NAM VA NU '
   FROM NHANV
   
  --2a
   SELECT  *
   FROM NHANV

   --2C Hiển thị tổng số đề án mà nhân viên đã làm khi có hành động xóa trên bảng Phancong.
    