-- A) 
SELECT * 
FROM CHUNGTU
WHERE CHUNGTU.LOAI = 'NHAP' AND YEAR(NGAYLAP) = 2021

-- B)
SELECT VATTU.MAVT, TENVT, SUM(SOLUONG)
FROM CTCHUNGTU, VATTU, CHUNGTU
WHERE CTCHUNGTU.MAVT = VATTU.MAVT AND CHUNGTU.MACT = CTCHUNGTU.MACT AND CHUNGTU.LOAI = 'NHAP'
GROUP BY VATTU.MAVT

-- C)
SELECT VT.MAVT, VT.TENVT, VT.DONGIA
FROM CTCHUNGTU CTCT, VATTU VT, CHUNGTU CT
WHERE CTCT.MAVT = VT.MAVT AND CT.MACT = CT.MACT AND CT.LOAI = 'NHAP' AND CTCT.SOLUONG >= ALL(SELECT SOLUONG FROM CTCHUNGTU)

-- D)
SELECT LOAI, SUM(TRIGIA) AS 'TONG GIA TRI'
FROM CHUNGTU CT
WHERE MONTH(NGAYLAP)<=6 AND YEAR(NGAYLAP) = 2022
GROUP BY LOAI

-- E)
SELECT MAKHO, TENKHO, DIACHI
FROM KHO, CHUNGTU CT, CTCHUNGTU CTCT
WHERE KHO.MAKHO = CT.MAKHO AND CT.MACT = CTCT.MACT AND CTCT.MAVT = 'VT003' OR CTCT.MAVT = 'VT004' AND CT.LOAI = 'NHAP'

-- F)
SELECT MACT, SUM(SOLUONG*DONGIA) AS 'TONG THANH TIEN'
FROM CTCHUNGTU
GROUP BY MACT


--BAI 2)
-- A)
SELECT TENPHIM
FROM PHIM, XUONGPHIM
WHERE PHIM.TENXUONG = XUONGPHIM.TENXUONG AND PHIM.TENXUONG = 'DISNEY' AND YEAR(PHIM.NAMSX) = 1990

-- B)
SELECT TENPHIM
FROM PHIM
WHERE THOILUONG >= ALL(SELECT THOILUONG FROM PHIM)

-- C)
SELECT MAPHIM, TENPHIM, COUNT(TENPHIM) AS 'SO LAN XUAT HIEN'
FROM PHIM
GROUP BY MAPHIM
HAVING COUNT(TENPHIM) >= 2